# Generated by Django 4.0.1 on 2022-01-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='address',
        ),
    ]
